# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CSDD eksāmeni Rīgā - A Kategorija
email: madeit.lv@gmail.com
description: Paātrini nokļūšanu CSDD eksāmenā
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://you.madeit.lv" # the base hostname & protocol for your site
github_username:  RonnyLV

# Build settings
markdown: kramdown
